// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

//! Cargo.toml generation logic.

mod generation;
mod generator;

pub use generator::CargoGenerator;
pub use generator::GenerationOutput;

/// Preamble that can be found on the first line of an autocargo generated file
pub static GENERATED_PREAMBLE: &str = "\x40generated by autocargo";
